apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    chart: elasticsearch
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.17.5
    helm:
      releaseName: elasticsearch
      valuesObject:    
        namespaceOverride: "logging"
        master:
          masterOnly: true
          replicaCount: 1
          persistence:
            enabled: true
            storageClass: "standard"
          resources:
            limits:
              cpu: 750m
            requests:
              cpu: 250m
        data:
          replicaCount: 1
          persistence:
            enabled: true
            storageClass: "standard"
          resources:
            limits: {}
            requests:
              cpu: 100m
        coordinating:
          replicaCount: 1
        ingest:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - createNamespace=true