apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.9.0
    helm:
      releaseName: kibana
      valuesObject:
        persistence:
          enabled: true
          storageClass: "standard"
          size: 5Gi
        ingress:
          enabled: true
          pathType: Prefix
          hostname: logging.tskmstr.mooo.com
          path: /
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        elasticsearch:
          hosts:
            - elasticsearch.logging.svc.cluster.local
          port: 9200
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - createNamespace=true