apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ default "default" .Values.namespace }}
data:
  FLASK_APP: movie_library
  FLASK_DEBUG: "0"
  FLASK_ENV: production