apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-config
  namespace: {{ default "default" .Values.namespace }}
data:
  nginx.conf: |-
    events {
      worker_connections 768;
    }

    http {
      include /etc/nginx/mime.types;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      server {
        listen 80 default_server;

        location /static {
          root /usr/share/nginx/html;
          try_files $uri $uri/;
        }

        location / {
          proxy_pass http://0.0.0.0:5000;
          proxy_redirect off;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /metrics {
          proxy_pass http://0.0.0.0:5000;
          proxy_redirect off;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }