---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgBBOeWBzCSRAupE85OqhgDuYF4kmshFt4OTvWZtz/TbX+L/pMY3pwWPTJzpW0qLLNon9imAt6u9PjmqcPCzzwjKNb8SD36IpQpcdswCYlpxZQ1n6OFph6XxGoRo/7bepoj8/dLYisb8LnLpJv43ad9dKQubzYXPWiCqwvETKJF9/JvCsSO0WkApJG+h2RJeln37uEOWMpX4gRIRb8xaBvRF/9YrriwxnZTMJ1xDrFuvUIM4gDUdVp16+69MEkiIKraPJ492uLlhcd1K/LVTvG5VjbRYvo/F0tQdi9q9CUrlA+GVYzpG54HiJ6AXp0Xa6nghqouDRkr6QGnnD2CjjtK0JOfHbzyqrJHGfhoYVU27j5LwMAHaHxy6toD2WB12IQUq2RvvISsH2nG9zp1ASYs18S6YVdtWRvErhCnbYekLaJpvt5NKL8sWlKz3Zo4FV/R1LjIF2EdEXqyYP8ul18RU6nU9nPw4sfG5YewszttHrb6hEtklDRltL2AY8X3DqdZf8e96rJN+cK6pRibJfl4ex24EXgVCKr5cXHmzEUzGim/U+qMRV3Kde65SOpRU/jxKoLLgXlkjf3l/u2r97CQgDzl2hn1hUGgH/VBMlLm/ofkYpMUe5vhFDULOU7F81hMwn28Mc1LqwnoyL5zwQG5Hxc4mOnYPmPAqJbQAd7rM+XmbLOmFoQAs99Rvke7LCWzcxkjvY2IgsmcB+oo7zmjqYqsWF7t/2DNi6VFbKwasmIrEDpAmHtlK5Zk7UniKPmJi5jovuSdP11R0XCFW84pOrod8YRskgxhn1EpWKf0Ur56M/0LQImRiqLFgXdVrA2G7u5M1faZd1IgpkjWKGfQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
