apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ default "default" .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}-svc
    prometheus.io/scrape: "true"
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
